a = input('Digite algo: ')
print('O tipo primitivo é', type(a))
print('Só tem espaço?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Esta em maiusculo?', a.isupper())
print('Esta em minusculo?', a.islower())
print('está capitalizada?', a.istitle())